/**
 * Kenya counties and towns - shared across onboarding and profile edit.
 * 47 counties (2010 Constitution). County capitals and sub-county towns as selectable cities.
 * Source: Wikipedia - Counties of Kenya, Sub-counties of Kenya.
 */
export const KENYA_GEOGRAPHY: Record<string, string[]> = {
  "Baringo": ["Kabarnet", "Kabartonjo", "Eldama Ravine", "Marigat", "Mogotio"],
  "Bomet": ["Bomet", "Sotik", "Litein", "Chepalungu", "Longisa"],
  "Bungoma": ["Bungoma", "Webuye", "Kimilili", "Chwele", "Sirisia", "Kapsokwony"],
  "Busia": ["Busia", "Malaba", "Funyula", "Amagoro", "Budalangi"],
  "Elgeyo-Marakwet": ["Iten", "Kapsowar", "Tambach", "Chebiemit", "Chepkorio"],
  "Embu": ["Embu", "Runyenjes", "Siakago", "Manyatta"],
  "Garissa": ["Garissa", "Modogashe", "Ijara", "Bura", "Fafi", "Lagdera"],
  "Homa Bay": ["Homa Bay", "Oyugis", "Mbita", "Ndhiwa", "Rangwe", "Suba"],
  "Isiolo": ["Isiolo", "Garbatula", "Merti", "Kinna", "Chari"],
  "Kajiado": ["Kajiado", "Ngong", "Kiserian", "Kitengela", "Loitoktok", "Oloitokitok"],
  "Kakamega": ["Kakamega", "Mumias", "Malava", "Shinyalu", "Butere", "Lugari", "Lumakanda"],
  "Kericho": ["Kericho", "Litein", "Kipkelion", "Sotik", "Bureti"],
  "Kiambu": ["Kiambu", "Thika", "Ruiru", "Limuru", "Gatundu", "Kikuyu", "Githunguri", "Lari"],
  "Kilifi": ["Kilifi", "Malindi", "Mtwapa", "Mariakani", "Kaloleni", "Rabai"],
  "Kirinyaga": ["Kerugoya", "Kutus", "Baricho", "Wanguru", "Sagana"],
  "Kisii": ["Kisii", "Ogembo", "Keroka", "Suneka", "Nyamarambe", "Masimba"],
  "Kisumu": ["Kisumu", "Awasi", "Muhoroni", "Maseno", "Kondele", "Nyando"],
  "Kitui": ["Kitui", "Mwingi", "Mutomo", "Kibwezi", "Kyuso", "Migwani"],
  "Kwale": ["Kwale", "Ukunda", "Msambweni", "Lunga Lunga", "Kinango", "Matuga"],
  "Laikipia": ["Rumuruti", "Nanyuki", "Nyahururu", "Ol Kalou", "Dol Dol", "Mukogodo"],
  "Lamu": ["Lamu", "Mpeketoni", "Faza", "Witu", "Kiunga"],
  "Machakos": ["Machakos", "Kangundo", "Athi River", "Tala", "Mwala", "Yatta", "Kathiani"],
  "Makueni": ["Wote", "Kibwezi", "Makindu", "Sultan Hamud", "Mtito Andei", "Kathonzweni", "Mbooni"],
  "Mandera": ["Mandera", "El Wak", "Rhamu", "Takaba", "Lafey", "Banissa"],
  "Marsabit": ["Marsabit", "Moyale", "Laisamis", "North Horr", "Sololo"],
  "Meru": ["Meru", "Maua", "Chuka", "Nkubu", "Tigania", "Imenti", "Igembe"],
  "Migori": ["Migori", "Rongo", "Kehancha", "Kegonga", "Uriri", "Awendo", "Nyatike"],
  "Mombasa": ["Mombasa", "Nyali", "Likoni", "Changamwe", "Kisauni", "Mvita"],
  "Murang'a": ["Murang'a", "Kangema", "Maragua", "Kandara", "Kigumo", "Gatanga", "Kenol"],
  "Nairobi": ["Nairobi", "Westlands", "Dagoretti", "Langata", "Kasarani", "Embakasi", "Starehe", "Makadara"],
  "Nakuru": ["Nakuru", "Naivasha", "Molo", "Gilgil", "Njoro", "Rongai", "Subukia", "Bahati"],
  "Nandi": ["Kapsabet", "Kabiyet", "Kabujoi", "Nandi Hills", "Tinderet", "Aldai"],
  "Narok": ["Narok", "Kilgoris", "Ololulung'a", "Trans Mara", "Narok North", "Narok South"],
  "Nyamira": ["Nyamira", "Keroka", "Nyansiongo", "Borabu", "Manga"],
  "Nyandarua": ["Ol Kalou", "Nyahururu", "Engineer", "Ndaragwa", "Kipipiri", "Kinangop"],
  "Nyeri": ["Nyeri", "Karatina", "Othaya", "Mukurweini", "Tetu", "Mathira", "Kieni"],
  "Samburu": ["Maralal", "Baragoi", "Wamba", "South Horr", "Archers Post"],
  "Siaya": ["Siaya", "Bondo", "Ugunja", "Yala", "Rarieda", "Gem", "Ugenya"],
  "Taita-Taveta": ["Mwatate", "Wundanyi", "Voi", "Taveta", "Mbololo"],
  "Tana River": ["Hola", "Garsen", "Madogo", "Bura", "Galole"],
  "Tharaka-Nithi": ["Kathwana", "Chuka", "Marimanti", "Magumoni", "Chogoria"],
  "Trans-Nzoia": ["Kitale", "Endebess", "Kiminini", "Saboti", "Kwanza"],
  "Turkana": ["Lodwar", "Lokichar", "Lokitaung", "Kakuma", "Kalokol", "Kainuk"],
  "Uasin Gishu": ["Eldoret", "Kesses", "Moiben", "Soy", "Turbo", "Ainabkoi"],
  "Vihiga": ["Mbale", "Vihiga", "Luanda", "Emuhaya", "Hamisi", "Sabatia"],
  "Wajir": ["Wajir", "Habaswein", "Bute", "Eldas", "Tarbaj", "Wajir North", "Wajir East"],
  "West Pokot": ["Kapenguria", "Kacheliba", "Sigor", "Chepareria", "Lomut"],
};
