/**
 * South Africa provinces and municipalities/towns - shared across onboarding and profile edit.
 * 9 provinces with 8 metros + 44 districts + 205 local municipalities (post-2016 boundary reform).
 * Municipality seats used as selectable cities. Source: Wikipedia - Municipalities of South Africa.
 */
export const SOUTH_AFRICA_GEOGRAPHY: Record<string, string[]> = {
  "Eastern Cape": [
    "East London",
    "Gqeberha",
    "Port Elizabeth",
    "Mount Ayliff",
    "Alice",
    "Barkly East",
    "Bizana",
    "Cala",
    "Cofimvaba",
    "Cradock",
    "Dutywa",
    "Flagstaff",
    "Gcuwa",
    "Graaff-Reinet",
    "Grahamstown",
    "Jeffreys Bay",
    "Kareedouw",
    "Kirkwood",
    "Komga",
    "Lady Frere",
    "Lady Grey",
    "Libode",
    "Maclear",
    "Matatiele",
    "Mount Frere",
    "Mthatha",
    "Ngcobo",
    "Ntabankulu",
    "Peddie",
    "Port Alfred",
    "Port St Johns",
    "Queenstown",
    "Qumbu",
    "Somerset East",
    "Stutterheim",
  ],
  "Free State": [
    "Bloemfontein",
    "Bethlehem",
    "Bothaville",
    "Bultfontein",
    "Boshof",
    "Frankfort",
    "Ficksburg",
    "Koffiefontein",
    "Kroonstad",
    "Ladybrand",
    "Phuthaditjhaba",
    "Parys",
    "Reitz",
    "Sasolburg",
    "Theunissen",
    "Trompsburg",
    "Vrede",
    "Welkom",
    "Zastron",
  ],
  "Gauteng": [
    "Johannesburg",
    "Pretoria",
    "Germiston",
    "Randburg",
    "Carletonville",
    "Heidelberg",
    "Krugersdorp",
    "Meyerton",
    "Randfontein",
    "Vanderbijlpark",
  ],
  "KwaZulu-Natal": [
    "Durban",
    "Camperdown",
    "Creighton",
    "Dannhauser",
    "Dundee",
    "Eshowe",
    "Estcourt",
    "Greytown",
    "Harding",
    "Howick",
    "Hlabisa",
    "Impendle",
    "Ixopo",
    "Jozini",
    "Kokstad",
    "KwaDukuza",
    "KwaMbonambi",
    "Kwangwanase",
    "Ladysmith",
    "Mandeni",
    "Maphumulo",
    "Melmoth",
    "Mkuze",
    "Mooi River",
    "Mtubatuba",
    "Ndwedwe",
    "Newcastle",
    "Nkandla",
    "Nongoma",
    "Nquthu",
    "Paulpietersburg",
    "Pietermaritzburg",
    "Port Shepstone",
    "Richmond",
    "Richards Bay",
    "Scottburgh",
    "Bergville",
    "Mtwalume",
    "Tugela Ferry",
    "Ulundi",
    "Umzimkhulu",
    "Utrecht",
    "Vryheid",
    "Wartburg",
  ],
  "Limpopo": [
    "Apel",
    "Bela-Bela",
    "Chuniespoort",
    "Dendron",
    "Giyani",
    "Groblersdal",
    "Hoedspruit",
    "Jane Furse",
    "Louis Trichardt",
    "Lephalale",
    "Malamulele",
    "Marble Hall",
    "Modimolle",
    "Modjadjiskloof",
    "Mokopane",
    "Musina",
    "Phalaborwa",
    "Polokwane",
    "Senwabarwana",
    "Thabazimbi",
    "Thohoyandou",
    "Tzaneen",
  ],
  "Mpumalanga": [
    "Balfour",
    "Belfast",
    "Bushbuckridge",
    "Carolina",
    "Delmas",
    "Ermelo",
    "Malalane",
    "Middelburg",
    "Nelspruit",
    "Piet Retief",
    "Secunda",
    "Siyabuswa",
    "Standerton",
    "Lydenburg",
    "eMalahleni",
    "Volksrust",
  ],
  "North West": [
    "Brits",
    "Christiana",
    "Delareyville",
    "Ganyesa",
    "Klerksdorp",
    "Lichtenburg",
    "Mahikeng",
    "Makapanstad",
    "Mogwase",
    "Potchefstroom",
    "Rustenburg",
    "Schweizer-Reneke",
    "Setlagole",
    "Taung",
    "Vryburg",
    "Wolmaransstad",
    "Zeerust",
    "Koster",
  ],
  "Northern Cape": [
    "Barkly West",
    "Calvinia",
    "Carnarvon",
    "Colesberg",
    "Daniëlskuil",
    "De Aar",
    "Douglas",
    "Garies",
    "Groblershoop",
    "Hartswater",
    "Hopetown",
    "Kakamas",
    "Kathu",
    "Kimberley",
    "Kuruman",
    "Mothibistad",
    "Petrusville",
    "Pofadder",
    "Port Nolloth",
    "Postmasburg",
    "Prieska",
    "Springbok",
    "Upington",
    "Victoria West",
    "Warrenton",
    "Williston",
  ],
  "Western Cape": [
    "Cape Town",
    "Ashton",
    "Beaufort West",
    "Bredasdorp",
    "Caledon",
    "Ceres",
    "Clanwilliam",
    "George",
    "Hermanus",
    "Knysna",
    "Ladismith",
    "Laingsburg",
    "Malmesbury",
    "Mossel Bay",
    "Oudtshoorn",
    "Paarl",
    "Piketberg",
    "Plettenberg Bay",
    "Prince Albert",
    "Riversdale",
    "Stellenbosch",
    "Swellendam",
    "Vredenburg",
    "Vredendal",
    "Worcester",
    "Moorreesburg",
  ],
};

